# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to configuration.nix instead.
#
# Captured 2026-07-19 from the running machine (phylax@192.168.85.30).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9f0a2d21-4a10-4a18-b229-307da1c2ee33";
      fsType = "ext4";
    };

  # ESP mounted at /boot/efi (not /boot) so GRUB keeps kernels on the ext4
  # root and only its stub lands on this cramped 96MB Windows-shared ESP.
  # /boot itself is a plain directory on the ext4 root. UUID unchanged.
  # nofail + short device-timeout: the ESP is only needed at nixos-rebuild time
  # (to write the GRUB stub), NEVER at runtime. This box shares the FAT ESP with
  # Windows, which keeps leaving the FAT dirty bit set (Fast Startup / updates);
  # a dirty FS fails systemd-fsck@boot-efi, and without nofail that failure fails
  # local-fs.target → the headless box drops to an emergency root-password prompt
  # with no sshd. nofail makes fsck/mount non-fatal so boot continues and stays
  # remotely reachable. Remount by hand (mount /boot/efi) before a rebuild.
  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/EC72-7C23";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "nofail" "x-systemd.device-timeout=5s" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
